### ISSUE TITLE
kolibri fails to start

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#152] opened 2020-01-31 16:30 UTC
tracker issue for https://community.learningequality.org/t/kolibri-failed-to-start-additional-information-can-be-found/1394

**Comment by mrpau-richard** [comment] 2020-02-03 09:06
The cause of this issue is the `options.ini` filled with incorrect values. I reported another issue [here](https://github.com/learningequality/kolibri/issues/6513) to fix this

**Comment by cpauya** [comment] 2020-03-27 06:28
Issue was not reproduced from our side and the user who reported the issue did not reply yet.

We are moving this to 1.3.7 milestone until we get more information how to reproduce this.

**Comment by mrpau-richard** [comment] 2020-06-11 09:14
Let's close this issue for now and reopen it when reproduce the issue.

**Closed by mrpau-richard** 2020-06-11 09:14 UTC
