### ISSUE TITLE
Font/Encoding issue in Spanish, with Python 3 installer

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#72] opened 2018-05-29 08:57 UTC
Issue occurs with the this [installer](https://github.com/learningequality/kolibri-installer-windows/pull/68#issue-187134084) from #68, when Spanish is selected as the default installation language.

![win10 start running - oracle vm virtualbox_163](https://user-images.githubusercontent.com/1457929/40648039-ae0e6540-632d-11e8-9463-901214519ec3.png)

However, I could not reproduce the issue with this [installer that still uses Python 2](https://github.com/learningequality/kolibri-installer-windows/pull/64#issuecomment-390870711), so still not sure if that is the cause... :confused:

**Comment by mrpau-richard** [comment] 2018-05-31 08:28
I have these `UnicodeDecodeError` error logs when using Spanish language.
```
File "c:\python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1554: character maps to <undefined>
```

**Comment by indirectlylit** [comment] 2018-06-01 16:20
@mrpau-richard would you post the complete stack trace? It's not clear to me where in the code this is happening.

**Comment by indirectlylit** [comment] 2018-06-01 16:27
FYI this looks very similar to another python3 windows issue we saw in the past: #2875

might be some clues there

**Comment by mrpau-richard** [comment] 2018-06-04 02:46
>@mrpau-richard would you post the complete stack trace? It's not clear to me where in the code this is happening.

@indirectlylit here's the [server.log](https://github.com/learningequality/kolibri-installer-windows/files/2066702/server.log)

**Comment by indirectlylit** [comment] 2018-06-04 03:12
All right - @mrpau-richard sounds like the `UnicodeDecodeError` was a false clue, and this issue is caused by something else.

Would you please continue to investigate? If we can't address it this week, we'll have to roll back #68 for this release

**Comment by mrpau-richard** [comment] 2018-06-07 09:12
@indirectlylit the cause of this issue is in the Windows system. I have this [reference](https://superuser.com/questions/239810/setting-utf8-as-default-character-encoding-in-windows-7)  saying that it's not possible to set the `utf-8` on Windows 7 as default.

At Windows 10 there's a beta `Use unicode UTF-8 for worldwide language support` option, at the `administrative language setting` this fixes this issue if you enable it at the Windows 10. But this option didn't exist at the `Windows 7`. 
![screen shot 2018-06-07 at 4 08 08 pm](https://user-images.githubusercontent.com/8663934/41088797-fa1c9e4c-6a72-11e8-8ef5-2f9302f0115a.png)

Let's use the Python 2.7 for now. This is a WIndows system settings issue we can't fix it on our side.

**Comment by indirectlylit** [comment] 2018-06-08 19:35
fixed by https://github.com/learningequality/kolibri/pull/3769

**Closed by indirectlylit** 2018-06-08 19:35 UTC
